USE `film-finder`;
insert into Employees (empID, firstName, lastName, role) values (1, 'Michale', 'Gives', 'Supervisor');
insert into Employees (empID, firstName, lastName, role) values (2, 'Chloe', 'Parres', 'Admin');
insert into Employees (empID, firstName, lastName, role) values (3, 'Jayson', 'Linden', 'Project Manager');
insert into Employees (empID, firstName, lastName, role) values (4, 'Liliane', 'Simonyi', 'Supervisor');
insert into Employees (empID, firstName, lastName, role) values (5, 'Gerta', 'Carnock', 'Project Manager');
insert into Employees (empID, firstName, lastName, role) values (6, 'Jefferey', 'Nunnery', 'UI Designer');
insert into Employees (empID, firstName, lastName, role) values (7, 'Farlay', 'Kaes', 'IT');
insert into Employees (empID, firstName, lastName, role) values (8, 'Norean', 'Fowley', 'IT');
insert into Employees (empID, firstName, lastName, role) values (9, 'Rickard', 'Sparks', 'Engineer');
insert into Employees (empID, firstName, lastName, role) values (10, 'Tamera', 'Abramchik', 'Engineer');
insert into Employees (empID, firstName, lastName, role) values (11, 'Cosmo', 'Jouandet', 'Project Manager');
insert into Employees (empID, firstName, lastName, role) values (12, 'Nahum', 'Beeckx', 'Admin');
insert into Employees (empID, firstName, lastName, role) values (13, 'Munmro', 'Ilyinski', 'Data Analyst');
insert into Employees (empID, firstName, lastName, role) values (14, 'Obediah', 'Tidy', 'UI Designer');
insert into Employees (empID, firstName, lastName, role) values (15, 'Kevyn', 'Welland', 'Data Analyst');
insert into Employees (empID, firstName, lastName, role) values (16, 'Stephanus', 'Hannay', 'Front-end Developer');
insert into Employees (empID, firstName, lastName, role) values (17, 'Boy', 'Purse', 'Front-end Developer');
insert into Employees (empID, firstName, lastName, role) values (18, 'Rinaldo', 'Brocklesby', 'Front-end Developer');
insert into Employees (empID, firstName, lastName, role) values (19, 'Alla', 'Mobius', 'Back-end Developer');
insert into Employees (empID, firstName, lastName, role) values (20, 'Hynda', 'Nicklinson', 'Back-end Developer');
insert into Employees (empID, firstName, lastName, role) values (21, 'Lamar', 'Synder', 'Engineer');
insert into Employees (empID, firstName, lastName, role) values (22, 'Stesha', 'Rihanek', 'Security Engineer');
insert into Employees (empID, firstName, lastName, role) values (23, 'Keriann', 'Bollom', 'Security Engineer');
insert into Employees (empID, firstName, lastName, role) values (24, 'Pate', 'Johnston', 'Software Architect');
insert into Employees (empID, firstName, lastName, role) values (25, 'Delainey', 'Craydon', 'Software Architect');
insert into Employees (empID, firstName, lastName, role) values (26, 'Kacie', 'Bourthouloume', 'Data Analyst');
insert into Employees (empID, firstName, lastName, role) values (27, 'Laurice', 'Ogbourne', 'Admin');
insert into Employees (empID, firstName, lastName, role) values (28, 'Langsdon', 'Birchenhead', 'IT');
insert into Employees (empID, firstName, lastName, role) values (29, 'Fowler', 'Flinn', 'Supervisor');
insert into Employees (empID, firstName, lastName, role) values (30, 'Mathian', 'Sexstone', 'Mobile Developer');
