insert into Movies (movieID, title, duration, yearReleased) values (1, '2010: The Year We Make Contact', 1.56, 1989);
insert into Movies (movieID, title, duration, yearReleased) values (2, 'Cross of Lorraine, The', 1.19, 1966);
insert into Movies (movieID, title, duration, yearReleased) values (3, 'Foxes', 1.02, 2012);
insert into Movies (movieID, title, duration, yearReleased) values (4, 'Catch .44', 1.15, 1972);
insert into Movies (movieID, title, duration, yearReleased) values (5, 'Keys of the Kingdom, The', 2.33, 2013);
insert into Movies (movieID, title, duration, yearReleased) values (6, 'Missing Picture, The (L''image manquante)', 1.87, 2015);
insert into Movies (movieID, title, duration, yearReleased) values (7, 'Flirting With Disaster', 1.95, 1963);
insert into Movies (movieID, title, duration, yearReleased) values (8, 'Bunker, The', 1.8, 1970);
insert into Movies (movieID, title, duration, yearReleased) values (9, 'Lord of Illusions', 2.66, 2019);
insert into Movies (movieID, title, duration, yearReleased) values (10, 'Across 110th Street', 2.71, 1980);
insert into Movies (movieID, title, duration, yearReleased) values (11, 'Debutantes, Los', 1.73, 1994);
insert into Movies (movieID, title, duration, yearReleased) values (12, 'Quest', 1.05, 2015);
insert into Movies (movieID, title, duration, yearReleased) values (13, 'Dances with Wolves', 2.91, 1993);
insert into Movies (movieID, title, duration, yearReleased) values (14, 'Beetle Queen Conquers Tokyo', 1.88, 2016);
insert into Movies (movieID, title, duration, yearReleased) values (15, 'You''re Not You', 1.63, 2020);
insert into Movies (movieID, title, duration, yearReleased) values (16, 'Wings of the Dove, The', 1.76, 1996);
insert into Movies (movieID, title, duration, yearReleased) values (17, 'Likeable Mister R, The (Simpaticul domn R)', 1.47, 1978);
insert into Movies (movieID, title, duration, yearReleased) values (18, 'Puss in Boots: The Three Diablos', 2.36, 1961);
insert into Movies (movieID, title, duration, yearReleased) values (19, 'All Access', 2.69, 1982);
insert into Movies (movieID, title, duration, yearReleased) values (20, 'Winged Creatures (Fragments)', 1.57, 1979);
insert into Movies (movieID, title, duration, yearReleased) values (21, 'Secret of Kells, The', 2.44, 1971);
insert into Movies (movieID, title, duration, yearReleased) values (22, 'Modern Problems', 2.96, 2001);
insert into Movies (movieID, title, duration, yearReleased) values (23, 'Das Experiment (Experiment, The)', 2.12, 2023);
insert into Movies (movieID, title, duration, yearReleased) values (24, 'Baytown Outlaws, The', 2.96, 2016);
insert into Movies (movieID, title, duration, yearReleased) values (25, 'Futurama: Bender''s Game', 1.71, 1967);
insert into Movies (movieID, title, duration, yearReleased) values (26, 'Shutter', 2.66, 2023);
insert into Movies (movieID, title, duration, yearReleased) values (27, 'The Man Who Loved Yngve', 2.03, 1983);
insert into Movies (movieID, title, duration, yearReleased) values (28, 'Three Smart Girls Grow Up', 2.26, 1993);
insert into Movies (movieID, title, duration, yearReleased) values (29, 'Alice in Wonderland', 1.49, 1988);
insert into Movies (movieID, title, duration, yearReleased) values (30, 'Hamlet', 1.74, 2023);
insert into Movies (movieID, title, duration, yearReleased) values (31, 'Europa Report', 2.59, 2013);
insert into Movies (movieID, title, duration, yearReleased) values (32, 'Brother (Hermano)', 2.7, 2008);
insert into Movies (movieID, title, duration, yearReleased) values (33, '5th Day of Peace (Dio è con noi)', 1.77, 2001);
insert into Movies (movieID, title, duration, yearReleased) values (34, 'Love Life', 1.4, 1961);
insert into Movies (movieID, title, duration, yearReleased) values (35, 'Child''s Pose', 2.05, 2014);
insert into Movies (movieID, title, duration, yearReleased) values (36, 'Wet Hot American Summer', 1.77, 2002);
insert into Movies (movieID, title, duration, yearReleased) values (37, 'Streetcar Named Desire, A', 1.02, 2010);
insert into Movies (movieID, title, duration, yearReleased) values (38, 'Girls Gone Dead', 2.18, 2000);
insert into Movies (movieID, title, duration, yearReleased) values (39, 'Big Shot''s Funeral (Da Wan)', 2.87, 1962);
insert into Movies (movieID, title, duration, yearReleased) values (40, 'Some Kind of Hero', 2.7, 2012);
insert into Movies (movieID, title, duration, yearReleased) values (41, 'Band Wagon, The', 1.89, 1985);
insert into Movies (movieID, title, duration, yearReleased) values (42, 'Burial Ground (a.k.a. Zombie Horror) (a.k.a. Zombie 3) (Notti del Terrore, Le)', 1.14, 2023);
insert into Movies (movieID, title, duration, yearReleased) values (43, 'Someday This Pain Will Be Useful to You', 1.23, 1972);
insert into Movies (movieID, title, duration, yearReleased) values (44, 'Krrish', 2.66, 2020);
insert into Movies (movieID, title, duration, yearReleased) values (45, 'Bottle Shock', 1.92, 2010);
insert into Movies (movieID, title, duration, yearReleased) values (46, 'Knights', 2.5, 2011);
insert into Movies (movieID, title, duration, yearReleased) values (47, 'Tito and Me (Tito i ja)', 1.88, 1991);
insert into Movies (movieID, title, duration, yearReleased) values (48, 'Paris Belongs to Us (Paris nous appartient)', 2.43, 1980);
insert into Movies (movieID, title, duration, yearReleased) values (49, 'Ladies of Leisure', 1.13, 1962);
insert into Movies (movieID, title, duration, yearReleased) values (50, 'Zapped!', 1.17, 2014);
