insert into Movies (movieID, title, duration, yearReleased) values (1, 'Curse of Frankenstein, The', 2.6, 2005);
insert into Movies (movieID, title, duration, yearReleased) values (2, 'Desi Boyz', 1.53, 1987);
insert into Movies (movieID, title, duration, yearReleased) values (3, 'Blueprint for Murder, A', 2.9, 2002);
insert into Movies (movieID, title, duration, yearReleased) values (4, 'Librarian: Quest for the Spear, The', 1.22, 1998);
insert into Movies (movieID, title, duration, yearReleased) values (5, 'Book of Love', 1.85, 2008);
insert into Movies (movieID, title, duration, yearReleased) values (6, 'Worthless, The (Arvottomat)', 1.24, 1986);
insert into Movies (movieID, title, duration, yearReleased) values (7, 'Interview with a Hitman', 2.69, 1985);
insert into Movies (movieID, title, duration, yearReleased) values (8, 'Kummeli Alivuokralainen', 2.33, 1990);
insert into Movies (movieID, title, duration, yearReleased) values (9, 'Big Night', 2.28, 1992);
insert into Movies (movieID, title, duration, yearReleased) values (10, 'Mirrors 2', 1.14, 1988);
insert into Movies (movieID, title, duration, yearReleased) values (11, 'Riding the Bullet', 1.55, 2001);
insert into Movies (movieID, title, duration, yearReleased) values (12, 'Conflict', 1.56, 2003);
insert into Movies (movieID, title, duration, yearReleased) values (13, 'Gunman''s Walk ', 2.99, 1996);
insert into Movies (movieID, title, duration, yearReleased) values (14, 'President''s Man, The', 1.12, 2001);
insert into Movies (movieID, title, duration, yearReleased) values (15, 'Charlie Chan and the Curse of the Dragon Queen', 2.88, 2005);
insert into Movies (movieID, title, duration, yearReleased) values (16, 'Pekka ja Pätkä salapoliiseina', 1.71, 2012);
insert into Movies (movieID, title, duration, yearReleased) values (17, 'Man from Monterey, The', 1.86, 2007);
insert into Movies (movieID, title, duration, yearReleased) values (18, 'Oh, Heavenly Dog!', 1.97, 1989);
insert into Movies (movieID, title, duration, yearReleased) values (19, 'Holiday Inn', 1.25, 2004);
insert into Movies (movieID, title, duration, yearReleased) values (20, 'Christmas Memory, A (Truman Capote''s ''A Christmas Memory'')', 1.67, 2001);
insert into Movies (movieID, title, duration, yearReleased) values (21, 'Dead Rising: Watchtower', 1.2, 2003);
insert into Movies (movieID, title, duration, yearReleased) values (22, 'Garage Olimpo', 1.93, 1992);
insert into Movies (movieID, title, duration, yearReleased) values (23, 'Rambo: First Blood Part II', 2.4, 1995);
insert into Movies (movieID, title, duration, yearReleased) values (24, 'Shine a Light', 2.38, 1996);
insert into Movies (movieID, title, duration, yearReleased) values (25, 'Foxfire', 1.71, 2003);
insert into Movies (movieID, title, duration, yearReleased) values (26, 'Billy Jack', 2.47, 2008);
insert into Movies (movieID, title, duration, yearReleased) values (27, 'Dr. Otto and the Riddle of the Gloom Beam', 1.3, 2010);
insert into Movies (movieID, title, duration, yearReleased) values (28, 'Die Hard: With a Vengeance', 1.52, 2005);
insert into Movies (movieID, title, duration, yearReleased) values (29, 'Lovely Molly', 2.66, 1998);
insert into Movies (movieID, title, duration, yearReleased) values (30, 'Linotype: The Film', 1.56, 2003);
