USE `film-finder`;
insert into Genres (genreID, name) values (1, 'Mystery');
insert into Genres (genreID, name) values (2, 'Comedy');
insert into Genres (genreID, name) values (3, 'Crime');
insert into Genres (genreID, name) values (4, 'Thriller');
insert into Genres (genreID, name) values (5, 'Drama');
insert into Genres (genreID, name) values (6, 'Romance');
insert into Genres (genreID, name) values (7, 'Action');
insert into Genres (genreID, name) values (8, 'Children');
insert into Genres (genreID, name) values (9, 'Fantasy');
insert into Genres (genreID, name) values (10, 'Horror');
insert into Genres (genreID, name) values (11, 'Sci-Fi');
insert into Genres (genreID, name) values (12, 'Adventure');
insert into Genres (genreID, name) values (13, 'Documentary');
insert into Genres (genreID, name) values (14, 'Animation');
insert into Genres (genreID, name) values (15, 'War');
insert into Genres (genreID, name) values (16, 'Tragedy');
insert into Genres (genreID, name) values (17, 'Feel-Good');
insert into Genres (genreID, name) values (18, 'Teen');
insert into Genres (genreID, name) values (19, 'Coming of Age');
insert into Genres (genreID, name) values (20, 'High School');
insert into Genres (genreID, name) values (21, 'Historical');
insert into Genres (genreID, name) values (22, 'Romantic Comedy');
insert into Genres (genreID, name) values (23, 'Action-Horror');
insert into Genres (genreID, name) values (24, 'Musical');
insert into Genres (genreID, name) values (25, 'Horror-Thriller');
