USE `film-finder`;
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (1, 'Nam dui.', '2025-07-16 10:30:44', 'open', 11, 24);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (2, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2025-05-09 13:14:00', 'resolved', 16, 16);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (3, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2025-11-01 07:33:51', 'resolved', 27, 29);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (4, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2025-02-09 14:38:03', 'in progress', 28, 23);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (5, 'Nulla ut erat id mauris vulputate elementum.', '2025-09-01 20:06:16', 'open', 8, 11);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (6, 'Morbi non lectus.', '2025-09-17 03:35:06', 'in progress', 27, 19);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (7, 'Donec dapibus.', '2025-09-30 19:27:45', 'resolved', 25, 17);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (8, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2025-11-07 09:28:33', 'in progress', 16, 18);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (9, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2025-07-18 16:11:39', 'pending', 25, 22);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (10, 'Aliquam erat volutpat. In congue. Etiam justo.', '2025-01-04 22:19:54', 'in progress', 13, 23);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (11, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2025-04-08 21:09:57', 'pending', 14, 17);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (12, 'Proin risus.', '2025-07-03 13:26:00', 'pending', 14, 5);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (13, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2025-04-17 06:16:04', 'in progress', 6, 18);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (14, 'Morbi a ipsum. Integer a nibh.', '2025-11-04 11:58:17', 'in progress', 6, 27);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (15, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2025-07-28 15:35:20', 'in progress', 26, 7);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (16, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2024-12-31 02:06:48', 'open', 25, 21);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (17, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-11-05 12:28:53', 'in progress', 13, 12);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (18, 'Donec dapibus. Duis at velit eu est congue elementum.', '2025-02-20 04:05:44', 'closed', 19, 10);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (19, 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2025-08-28 16:58:31', 'in progress', 14, 29);
insert into MOCK_DATA (requestID, message, timestamp, status, userID, empID) values (20, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-03-28 13:35:08', 'resolved', 1, 19);
