USE `film-finder`;
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (1, '10/2/2025', null, 'Mauris sit amet eros.', 11);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (2, '1/19/2025', null, 'Aliquam quis turpis eget elit sodales scelerisque.', 11);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (3, '9/21/2025', '2/24/2025', 'Nullam varius. Nulla facilisi.', 27);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (4, '7/20/2025', '11/22/2024', 'Sed vel enim sit amet nunc viverra dapibus.', null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (5, '11/3/2024', '12/4/2025', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 7);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (6, '11/20/2025', null, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 21);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (7, '12/2/2024', null, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 24);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (8, '7/14/2025', '12/24/2024', null, null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (9, '6/24/2025', '9/16/2025', 'Fusce consequat. Nulla nisl. Nunc nisl.', 5);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (10, '5/24/2025', '7/10/2025', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (11, '9/3/2025', null, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (12, '9/19/2025', '3/27/2025', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 22);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (13, '8/16/2025', '12/1/2025', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (14, '12/21/2024', '2/6/2025', 'Maecenas rhoncus aliquam lacus.', 12);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (15, '3/23/2025', '2/27/2025', null, 5);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (16, '3/9/2025', '7/25/2025', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 9);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (17, '3/25/2025', '12/7/2025', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (18, '1/24/2025', '7/31/2025', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 9);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (19, '7/25/2025', '3/17/2025', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', null);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (20, '3/5/2025', '12/6/2025', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 12);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (21, '4/3/2025', '4/13/2025', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 15);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (22, '11/16/2025', '9/30/2025', null, 27);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (23, '6/11/2025', '8/7/2025', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 14);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (24, '12/16/2024', '2/28/2025', null, 16);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (25, '9/27/2025', '11/17/2024', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 13);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (26, '4/25/2025', '5/13/2025', 'Sed ante. Vivamus tortor.', 26);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (27, '11/24/2025', '5/16/2025', null, 5);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (28, '7/19/2025', '8/14/2025', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 9);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (29, '11/24/2024', '4/26/2025', null, 11);
insert into Tasks (taskID, createdAt, completedAt, description, empID) values (30, '12/15/2024', '6/14/2025', 'Curabitur gravida nisi at nibh.', 18);
