USE `film-finder`;
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (1, '1/20/2025', '12/10/2024', null, 11);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (2, '1/23/2025', '3/3/2025', 'Donec dapibus.', null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (3, null, '5/25/2025', null, null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (4, '3/23/2025', '1/1/2025', 'Ut tellus.', 15);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (5, '5/16/2025', null, null, 23);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (6, '8/4/2025', '3/15/2025', 'Etiam faucibus cursus urna.', 2);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (7, '9/11/2025', '11/8/2024', null, 26);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (8, null, '12/19/2024', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 12);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (9, null, '1/14/2025', 'Curabitur in libero ut massa volutpat convallis.', null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (10, null, '9/25/2025', 'Nulla suscipit ligula in lacus.', null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (11, null, '9/12/2025', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 26);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (12, '10/13/2025', null, null, null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (13, '4/26/2025', '2/23/2025', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 24);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (14, null, '3/11/2025', null, 10);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (15, '7/29/2025', '4/14/2025', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 5);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (16, '10/25/2025', '7/14/2025', null, 18);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (17, '8/22/2025', null, null, null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (18, '12/18/2024', null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 30);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (19, '11/27/2024', '7/24/2025', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 14);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (20, '3/31/2025', '11/16/2025', 'Morbi ut odio.', 1);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (21, null, '1/29/2025', null, 4);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (22, '12/13/2024', null, 'Praesent id massa id nisl venenatis lacinia.', 29);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (23, '12/25/2024', '3/14/2025', null, 21);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (24, '9/14/2025', '7/16/2025', 'Nunc purus.', 4);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (25, null, '4/12/2025', null, null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (26, '2/8/2025', '1/13/2025', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (27, '9/2/2025', '12/28/2024', null, 12);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (28, '8/21/2025', null, 'Nulla ac enim.', null);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (29, '3/21/2025', '8/17/2025', 'Suspendisse potenti. In eleifend quam a odio.', 23);
insert into AppVersions (versionID, createdAt, publishedAt, description, empID) values (30, '10/28/2025', '2/1/2025', 'Vivamus tortor. Duis mattis egestas metus.', null);
