USE `film-finder`;
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (1, null, '9/20/2025', 'Duis aliquam convallis nunc.', null);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (2, '10/12/2025', '4/12/2025', null, 29);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (3, null, null, null, 7);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (4, '3/28/2025', '11/18/2024', 'Phasellus sit amet erat. Nulla tempus.', 10);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (5, '12/6/2024', null, 'Cras pellentesque volutpat dui.', 1);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (6, null, '1/6/2025', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', null);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (7, '12/12/2024', '10/16/2025', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 9);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (8, '12/3/2024', '9/15/2025', 'Integer ac neque.', 4);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (9, null, '3/26/2025', 'Pellentesque ultrices mattis odio.', 1);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (10, null, '1/31/2025', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 30);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (11, '3/31/2025', '9/6/2025', 'Vivamus in felis eu sapien cursus vestibulum.', 11);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (12, '9/25/2025', '11/11/2024', 'Vivamus in felis eu sapien cursus vestibulum.', 30);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (13, null, '11/15/2024', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 28);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (14, '9/10/2025', null, 'Vivamus tortor.', 6);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (15, '6/20/2025', null, null, null);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (16, '5/10/2025', null, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 4);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (17, '3/1/2025', '7/31/2025', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 30);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (18, '8/8/2025', '6/11/2025', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 12);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (19, '2/18/2025', '2/18/2025', null, 8);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (20, '5/24/2025', '2/10/2025', null, 20);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (21, '12/4/2024', null, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 8);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (22, '5/18/2025', '3/6/2025', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 26);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (23, null, '9/4/2025', 'Nullam molestie nibh in lectus. Pellentesque at nulla.', null);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (24, '11/3/2025', '9/26/2025', null, 19);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (25, '5/11/2025', '10/19/2025', 'Morbi a ipsum. Integer a nibh. In quis justo.', 7);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (26, '2/13/2025', '6/25/2025', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 3);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (27, '8/17/2025', '7/24/2025', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 13);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (28, '6/4/2025', '6/13/2025', 'Praesent lectus.', 14);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (29, '8/22/2025', null, 'Duis mattis egestas metus. Aenean fermentum.', 11);
insert into MOCK_DATA (versionID, createdAt, publishedAt, description, empID) values (30, '10/2/2025', '1/17/2025', null, 2);
